[package]
name = "playground"
version = "0.1.0"
edition = "2021"

[dev-dependencies]

[dependencies]
csv = { path = "../csv" }
ndjson = { path = "../ndjson" }
combine = "*"
rand = "*"
chrono = "*"
mockall = "*"


